server:
  port: 8084
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10

spring:
  application:
    name: service.healthcare
  profiles:
    active: dev
    include: common

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.sleekydz86.service.healthcare.dto
    configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    loggers:
      enabled: true
  info:
    env:
      enabled: true

logging:
  config: classpath:log4j2-spring.xml

info:
  app:
    name: healthcare_mono Core Service
    description: Healthcare LifeLink Core Service
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}
