server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

h2:
  console:
    enabled: true
    settings:
      web_allow_others: true
    path: /h2-console

datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb

jpa:
  hibernate:
    ddl-auto: create-DROP #app실행시점에 테이블 지우고 다시 생성, 종료시 지움
  properties:
    hibernate:
      show_sql: true
      format_sql: true

logging:
  config: classpath:log4j2-spring.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  sleuth:
    zipkin:
      base-url: http://localhost:9411
    sampler:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  tracing:
    sampling:
      probability: 1.0
