package com.sleekydz86.service.commu.entity;

public enum DiseaseCategory {
    CANCER, LEUKEMIA, HYPERTENSION, DIABETES, ANGINA, MYOCARDIAL, INFARCTION, MITRAL, VALVE, PROLAPSE, STROKE, LIVERCIRRHOSIS, AIDS
}


