spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    com.sleekydz86: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG

debug: true

token:
  secret: healthcare-lifelink-jwt-secret-key-for-authentication-service-2025-dev
  access-expired-time: 3600000
  refresh-expired-time: 86400000
