server:
  port: 8080

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: api.gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: healthcare
              uri: lb://service.healthcare
              predicates:
                - Path=/healthcare/**
            - id: usermanagement
              uri: lb://service.usermanagement
              predicates:
                - Path=/management/**
            - id: community
              uri: lb://service.comm
              predicates:
                - Path=/community/**
          discovery:
            locator:
              enabled: true
    config:
      uri: http://localhost:8888
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    com.sleekydz86: DEBUG