server:
  port: 8080

spring:
  application:
    name: api.gateway
  cloud:
    gateway:
      routes:
        - id: healthcare
          uri: lb://service.healthcare
          predicates:
            - Path=/healthcare/**
        - id: usermanagement
          uri: lb://service.usermanagement
          predicates:
            - Path=/management/**
      discovery:
        locator:
          enabled: true
    config:
      uri: http://localhost:8888
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    mz.hc: DEBUG
