spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    root: INFO
    com.sleekydz86: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
