server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthcare_prod
    username: ${DB_USERNAME:healthcare_user}
    password: ${DB_PASSWORD:healthcare_pass}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 운영 환경 로깅
logging:
  level:
    root: WARN
    com.sleekydz86: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

# 운영용 설정
debug: false
