# service-commu 서비스 전용 설정

# 테스트 메시지
message: "Config Server에서 불러온 설정입니다!"

# 데이터베이스 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.sleekydz86: DEBUG

# 커스텀 설정
custom:
  feature:
    enabled: true
  timeout: 3000